### ISSUE TITLE
Can only load mnist dataset

### ISSUE THREAD

**Issue by connellybarnes** [znxlwm/pytorch-generative-model-collections#1]
Thanks for this cool codebase that allows one to use many GANs!

But it seems that only the mnist dataset can be loaded, because the other functions are missing from the utils module. For example, if I issue this command:

    python main.py --dataset celebA --gan_type WGAN --epoch 25 --batch_size 64

This results in the traceback:

    Traceback (most recent call last):                                                                          │·····
     File "main.py", line 107, in <module>                                                                     │·····
        main()                                                                                                  │·····
      File "main.py", line 86, in main                                                                          │·····
        gan = WGAN(args)                                                                                        │·····
      File "WGAN.py", line 130, in __init__             
    │self.data_loader = utils.load_celebA('data/celebA', transform=transforms.Compose(                       
    │AttributeError: module 'utils' has no attribute 'load_celebA'

**Comment by znxlwm** [comment]
Sorry! 

It is my mistake. I did not update the 'utils.py'

now update the 'utils.py' please check again.
